<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Savithri" failures="1" tests="10" name="Test" time="24.203" errors="0" timestamp="2025-06-14T13:35:12 IST">
  <testcase classname="testNgPractice.DataProviderpackage" name="createCustomer" time="0.025"/>
  <testcase classname="testNgPractice.DataProviderpackage" name="createCustomer" time="0.002"/>
  <testcase classname="testNgPractice.DataProviderpackage" name="createCustomer" time="0.007"/>
  <testcase classname="testNgPractice.DataProviderpackage" name="createCustomer" time="0.009"/>
  <testcase classname="testNgPractice.AssertionPractice" name="Softsample" time="0.026">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [1] but found [0]
at testNgPractice.AssertionPractice.Softsample(AssertionPractice.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Softsample -->
  <testcase classname="testNgPractice.AssertionPractice" name="hardsample" time="0.005"/>
  <testcase classname="testNgPractice.TestNgPractice" name="modify" time="0.001"/>
  <testcase classname="testNgPractice.TestNgPractice" name="create" time="0.001"/>
  <testcase classname="testNgPractice.TestNgPractice" name="delete" time="0.004"/>
  <testcase classname="testNgPractice.ADDLowestPriceProducttocartTC_002" name="AddLowestPriceproducttocarttest" time="11.767"/>
</testsuite> <!-- Test -->
